import{a as g}from"./assets/vendor-CR7N1gwd.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const y="45506482-0746cd613ccb32219c9653431",h="https://pixabay.com/api/";async function f(t,s=1,a=15){const n={key:y,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:a};try{return(await g.get(h,{params:n})).data}catch(e){throw console.error("Error fetching images:",e),e}}function p(t){return t.map(({webformatURL:s,tags:a,likes:n,views:e,comments:r,downloads:i})=>`
        <div class="image-frame">
          <img src="${s}" alt="${a}" loading="lazy" class="image" />
          <div class="text-block">
            <p>Likes: ${n}</p>
            <p>Views: ${e}</p>
            <p>Comments: ${r}</p>
            <p>Downloads: ${i}</p>
          </div>
        </div>`).join("")}function d(t){return`<p class="message">${t}</p>`}const L=document.querySelector(".gallery-form"),o=document.querySelector(".gallery-list"),u=document.querySelector(".load-more"),m=document.querySelector(".loader");let c=1,l="";L.addEventListener("submit",async t=>{if(t.preventDefault(),o.innerHTML="",u.classList.add("hidden"),c=1,l=t.target.elements.query.value.trim(),l!=="")try{const s=await f(l,c);if(s.totalHits===0){o.innerHTML=d("No images found.");return}o.innerHTML=p(s.hits),u.classList.remove("hidden")}catch{o.innerHTML=d("Something went wrong. Please try again.")}});u.addEventListener("click",async()=>{c+=1,m.classList.add("active");try{const t=await f(l,c);o.innerHTML+=p(t.hits),m.classList.remove("active"),t.totalHits<=c*15&&(u.classList.add("hidden"),o.innerHTML+=d("We're sorry, but you've reached the end of search results."))}catch{o.innerHTML+=d("Something went wrong. Please try again."),m.classList.remove("active")}});
//# sourceMappingURL=index.js.map
